### ISSUE TITLE
Decorated banners crash the game

### ISSUE THREAD

**Issue by TheUnknownBreeze** [ViaVersion/ViaFabricPlus#405]
### General Information

(this is the first time that i make an issue on github)
https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.2.0

`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-05-04 16:22:08
Description: Saving entity NBT

java.lang.IllegalStateException: Missing id for entity in: {patterns:[{color:"cyan",pattern:"rhombus"},{color:"light_gray",pattern:"stripe_bottom"},{color:"gray",pattern:"stripe_center"},{color:"light_gray",pattern:"border"},{color:"black",pattern:"stripe_middle"},{color:"light_gray",pattern:"half_horizontal"},{color:"light_gray",pattern:"circle"},{color:"black",pattern:"border"}]}
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:275)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:79)
	at net.minecraft.class_1799.method_57376(class_1799.java:388)
	at net.minecraft.class_1661.method_7384(class_1661.java:408)
	at net.minecraft.class_1657.method_5652(class_1657.java:881)
	at net.minecraft.class_1297.method_5647(class_1297.java:1860)
	at net.minecraft.class_897.handler$bik000$entityseparator$render(class_897.java:1546)
	at net.minecraft.class_897.method_3936(class_897.java)
	at net.minecraft.class_922.method_4054(class_922.java:154)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_490.method_29977(class_490.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1190)
	at net.minecraft.class_490.method_48472(class_490.java:156)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$212(class_757.java)
	at net.minecraft.class_757.wrapOperation$cej000$fabric-screen-api-v1$onRenderScreen(class_757.java:5101)
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:275)
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:79)
	at net.minecraft.class_1799.method_57376(class_1799.java:388)
	at net.minecraft.class_1661.method_7384(class_1661.java:408)
	at net.minecraft.class_1657.method_5652(class_1657.java:881)
	at net.minecraft.class_1297.method_5647(class_1297.java:1860)
	at net.minecraft.class_897.handler$bik000$entityseparator$render(class_897.java:1546)
	at net.minecraft.class_897.method_3936(class_897.java)
	at net.minecraft.class_922.method_4054(class_922.java:154)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_490.method_29977(class_490.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1190)
	at net.minecraft.class_490.method_48472(class_490.java:156)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$212(class_757.java)
	at net.minecraft.class_757.wrapOperation$cej000$fabric-screen-api-v1$onRenderScreen(class_757.java:5101)

-- Entity being saved --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 17377
	Entity Name: TheUnknownBreeze
	Entity's Exact location: -1840.41, 79.00, 431.18
	Entity's Block location: World: (-1841,79,431), Section: (at 15,15,15 in -116,4,26; chunk contains blocks -1856,-64,416 to -1841,319,431), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,-64,0 to -1537,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1297.method_5647(class_1297.java:1860)
	at net.minecraft.class_897.handler$bik000$entityseparator$render(class_897.java:1546)
	at net.minecraft.class_897.method_3936(class_897.java)
	at net.minecraft.class_922.method_4054(class_922.java:154)
	at net.minecraft.class_1007.method_4215(class_1007.java:68)
	at net.minecraft.class_1007.method_3936(class_1007.java:45)
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_490.method_29977(class_490.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1190)
	at net.minecraft.class_490.method_48472(class_490.java:156)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$212(class_757.java)
	at net.minecraft.class_757.wrapOperation$cej000$fabric-screen-api-v1$onRenderScreen(class_757.java:5101)
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 17377
	Entity Name: TheUnknownBreeze
	Entity's Exact location: -1840.41, 79.00, 431.18
	Entity's Block location: World: (-1841,79,431), Section: (at 15,15,15 in -116,4,26; chunk contains blocks -1856,-64,416 to -1841,319,431), Region: (-4,0; contains chunks -128,0 to -97,31, blocks -2048,-64,0 to -1537,319,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_490.method_29977(class_490.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1190)
	at net.minecraft.class_490.method_48472(class_490.java:156)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$212(class_757.java)
	at net.minecraft.class_757.wrapOperation$cej000$fabric-screen-api-v1$onRenderScreen(class_757.java:5101)
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@2a53221a
	Location: 0.00,0.00,0.00 - World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:143)
	at net.minecraft.class_490.method_29977(class_490.java:156)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1190)
	at net.minecraft.class_490.method_48472(class_490.java:156)
	at net.minecraft.class_490.method_2486(class_490.java:130)
	at net.minecraft.class_490.method_2389(class_490.java:99)
	at net.minecraft.class_465.method_25420(class_465.java:172)
	at net.minecraft.class_437.method_25394(class_437.java:129)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_485.method_25394(class_485.java:32)
	at net.minecraft.class_490.method_25394(class_490.java:81)
	at net.minecraft.class_437.method_47413(class_437.java:120)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$212(class_757.java)
	at net.minecraft.class_757.wrapOperation$cej000$fabric-screen-api-v1$onRenderScreen(class_757.java:5101)
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (293, 198). Absolute: (879.000000, 595.000000)
	Screen size: Scaled: (534, 279). Absolute: (1600, 837). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:922)
	at net.minecraft.class_310.method_1523(class_310.java:1320)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 356.580s
	Wall uptime: 276.839s
	High-res time: 156613.437s
	Client ticks: 4530 ticks / 226.500s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['TheUnknownBreeze'/17377, l='ClientLevel', x=-1840.41, y=79.00, z=431.18]]
	Chunk stats: 529, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,70,-112), Section: (at 0,6,0 in 3,4,-7; chunk contains blocks 48,-64,-112 to 63,319,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 10851769 game time, 15522219 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
	Tracked entity count: 64

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, alinlib, async-pack-scan, authme, autohud, backburner, bettercommandblockui, betterstats, book_and_quick_save, bundle_scroll, c2me, camoverlay, capes, cardinal-components, cardinal-components-base, cardinal-components-block, cardinal-components-chunk, cardinal-components-entity, cardinal-components-item, cardinal-components-level, cardinal-components-scoreboard, cardinal-components-world, cat_jam, chat_heads, chatshot, cicada, cloth-config, colorfulsubtitles, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, controlify, customclientbrand, customlevelcolour, dynamic_fps, elytratrims, entity_texture_features, entityculling, entityseparator, essential, essential-container, essential-loader, evilcreativefly, f3teverywhere, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fan_cake, fastquit, fpsreducer, guifollowers, immediatelyfast, itemswapper, jade, libbamboo, libjf, libjf-config-core-v2, libjf-config-network-v0, libjf-config-ui-tiny, libjf-translate-v1, libjf-web-v1, lighty, listentryhighlightfix, lithium, mambience, map_png, minepedia, modernfix, modmenu, morechathistory, moreculling, mr_footprint_particles, myresourcepack, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, nodimensionbackground, notebook, oldmclogo, particlerain, peek, pickblockpro, postmortalparticles, pwam, real-arrow-tip, resource_explorer, respackopts, roughlyenoughitems, rrls, scoreboard-overhaul, scoreboard-overhaul-common, showmapid, signcopy, skinlayers3d, smoke_signals, sound_physics_remastered, spark, tcdcommons, translucent-glass, useful-saved-hotbars, vanillazoom, viafabricplus, vistas, visuality, vmp, voicechat, wi_zoom, world_preview, yet_another_config_lib_v3, youwereslain, itemswapper:default, itemswapper:experimental_addon, white_icons, file/sus_sand_1.5.zip, file/§eExtended_lantern_1.20x.zip, file/JadeStardewValleyTheme.zip, file/rocketjump.zip, file/Alternate Ink.zip, file/blackstone-magma.zip, file/coal-texture.zip, file/da-vinci-gliders.zip, file/improved-crafting-table-v1-0.zip, file/§aDrodi's Slimes [Release].zip, file/expack-03-caladbolg.zip, file/anothercit-v1-0.zip, file/RavenPhantoms_v1.0.0.zip, backburner:notebook, translucent-glass:translucent-glass, file/pistonmace.zip, file/Biomeless Music 1.20.5.zip, essential

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 283115520 bytes (270 MiB) / 1046478848 bytes (998 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) HD Graphics 4000
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 10.18.10.4252
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 27395.45
	Virtual memory used (MB): 22144.78
	Swap memory total (MB): 15220.12
	Swap memory used (MB): 2816.06
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		alinlib: AlinLib 1.2.0-alpha.3
		architectury: Architectury 12.0.27
		areas: Areas 5.7
		async-pack-scan: Async Pack Scan 0.2.4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.0.5+c5f2432c0d
		authme: Auth Me 8.0.0+1.20.5
			fabric-api-base: Fabric API Base 0.4.40+80f8cf510d
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b30d
		autohud: Auto HUD 7.1+1.20.5
			libbamboo: libbamboo 1.14+1.20.5
		backburner: Back-burner 1.3.3+1.20.5
		badoptimizations: BadOptimizations 2.1.1
		bettercommandblockui: BetterCommandBlockUI 0.5.1
		betterstats: Better Statistics Screen 3.10+fabric-1.20.6
			tcdcommons: TCD Commons API 3.10+fabric-1.20.6
		book_and_quick_save: Book and Quick Save 1.1
		bundle_scroll: Bundle Scroll 1.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.95+1.20.6
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.95+1.20.6
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.95+1.20.6
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.95+1.20.6
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.95+1.20.6
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.95+1.20.6
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.95+1.20.6
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.95+1.20.6
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.95+1.20.6
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.95+1.20.6
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.95+1.20.6
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.95+1.20.6
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.95+1.20.6
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.95+1.20.6
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.95+1.20.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		camoverlay: CamOverlay 1.1.0-beta.2
			meteordevelopment_starscript: starscript 0.2.2
		capes: Capes 1.5.4+1.20.5
		cardinal-components: Cardinal Components API 6.0.0-beta.3
			cardinal-components-base: Cardinal Components API (base) 6.0.0-beta.3
			cardinal-components-block: Cardinal Components API (blocks) 6.0.0-beta.3
			cardinal-components-chunk: Cardinal Components API (chunks) 6.0.0-beta.3
			cardinal-components-entity: Cardinal Components API (entities) 6.0.0-beta.3
			cardinal-components-item: Cardinal Components API (items) 6.0.0-beta.3
			cardinal-components-level: Cardinal Components API (world saves) 6.0.0-beta.3
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 6.0.0-beta.3
			cardinal-components-world: Cardinal Components API (worlds) 6.0.0-beta.3
		cat_jam: cat_jam 1.2.1
		chat_heads: Chat Heads 0.11.0
		chatshot: ChatShot 1.0.0
		cicada: CICADA 0.7.1+1.20.5-and-above
		cloth-config: Cloth Config v14 14.0.126
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.56
		colorfulsubtitles: Colorful Subtitles 1.5.0
		controlify: Controlify 2.0.0-beta.7+1.20.6
			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_parsers_gson: gson 0.3.0
			org_quiltmc_parsers_json: json 0.3.0
		currentgamemusictrack: Current Game Music Track 1.6
		customclientbrand: Custom Client Brand 1.0.1+1.20.5
		customlevelcolour: Custom Level Colour 1.0.0+1.20.5
		dynamic_fps: Dynamic FPS 3.4.3
		elementa: Elementa 638
		elytratrims: Elytra Trims 3.1.2
			mixinsquared: MixinSquared 0.1.2-beta.4
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.4
		entityseparator: Entity Separator 0.2.3+1.20.5
		essential: Essential 1.3.2.2+gc6bc4f09d7
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		evilcreativefly: Creative Fly 1.3.3-1.20.5-fabric
		f3teverywhere: F3+T Everywhere 1.0.1
		fabric-api: Fabric API 0.97.8+1.20.6
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bff
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beff
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bff
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51ff
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51ff
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bff
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fff
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51ff
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3ff
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.4+b82b2392ff
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.3+7f945d5bff
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.0.0+2b43c5c8ff
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51ff
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.15+2a2c66b6ff
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.0.6+7f945d5bff
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913ff
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bff
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3ff
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51ff
			fabric-item-api-v1: Fabric Item API (v1) 8.1.1+17e985d6ff
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.38+aae0949aff
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51ff
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3ff
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.4+97f703daff
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837cff
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51ff
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7ff
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349ff
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.3+c5fc38b3ff
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3ff
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3ff
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.15+f1240ba7ff
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703daff
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51ff
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3ff
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eff
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedff
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3ff
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbff
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.0.1+74e2f560ff
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8aff
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.72+b21c00cbff
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3ff
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3ff
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560ff
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		fallingleaves: Falling Leaves 1.15.7
		fan_cake: FanCake ${version}
		fastquit: FastQuit 3.0.0+1.20.6
		ferritecore: FerriteCore 6.1.1
		fpsreducer: FPS Reducer 1.20.5-2.8
		guifollowers: GUI Followers 3.6
		immediatelyfast: ImmediatelyFast 1.2.13+1.20.6
			net_lenni0451_reflect: Reflect 1.3.2
		isxander-main-menu-credits: Main Menu Credits 1.2.0
		itemswapper: ItemSwapper 0.6.3
		jade: Jade 14.1.0+fabric
		java: OpenJDK 64-Bit Server VM 21
		libjf: LibJF 3.15.6
			libjf-base: LibJF Base 3.15.6
			libjf-config-commands: LibJF Config Commands 3.15.6
			libjf-config-core-v2: LibJF Config 3.15.6
			libjf-config-network-v0: LibJF Config: Network 3.15.6
			libjf-config-ui-tiny: LibJF Config UI: Tiny 3.15.6
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.15.6
			libjf-data-v0: LibJF Data 3.15.6
			libjf-mainhttp-v0: LibJF MainHTTP 3.15.6
			libjf-translate-v1: LibJF Translate 3.15.6
			libjf-unsafe-v0: LibJF Unsafe 3.15.6
			libjf-web-v1: LibJF Web 3.15.6
		lighty: Lighty 3.0.0-beta.1+1.20.5
		listentryhighlightfix: List Entry Highlight Fix 1.0.0
		lithium: Lithium 0.12.3
		mambience: MAmbience 5.5.0+1.20.6
		map_png: Map.png 1.0.1+1.20.6
		melody: Melody 1.0.6
		minecraft: Minecraft 1.20.6
		minepedia: Minepedia 1.1
		modernfix: ModernFix 5.17.2+mc1.20.6
		modmenu: Mod Menu 10.0.0-beta.1
		morechathistory: More Chat History 1.3.1
		moreculling: More Culling 0.25.0
			com_github_fallen-breath_conditional-mixin: conditional-mixin v0.6.2
		mr_footprint_particles: Footprint Particles 5
		myresourcepack: My Resource Pack, My Choice 1.2.1+1.20.5
		nodimensionbackground: No Dimension Background 1.1.0
		notebook: Notebook 4.0.0
		oldmclogo: Old MC Logo 1.1.3
		org_jetbrains_annotations: annotations 23.0.0
		particlerain: Particle Rain 2.0.8
		peek: Peek 1.20.6-1.3.1
		persistentinventorysearch: Persistent Inventory Search 1.4
		pickblockpro: Pick Block Pro 1.9.28-beta
		postmortalparticles: Postmortal Particles 1.0.0-1.20.x
		pwam: PasswordManager for AuthMe 0.0.9+fabric-1.20.6
			io_github_oshai_kotlin-logging-jvm: kotlin-logging-jvm 6.0.3
			net_kyori_adventure-api: adventure-api 4.9.3
			net_kyori_adventure-key: adventure-key 4.9.3
			net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.9.3
			net_kyori_examination-api: examination-api 1.3.0
			net_kyori_examination-string: examination-string 1.3.0
			org_jetbrains_exposed_exposed-core: exposed-core 0.49.0
			org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.49.0
			org_xerial_sqlite-jdbc: sqlite-jdbc 3.45.2.0
		real-arrow-tip: Real Arrow Tip 0.1.0+mc1.20.5
		resource_explorer: Resource Explorer 1.1
		respackopts: Resource Pack Options 4.8.0
			io_gitlab_jfronny_muscript-all: muscript-all 1.7-SNAPSHOT
			io_gitlab_jfronny_muscript-json: muscript-json 1.7-SNAPSHOT
		roughlyenoughitems: Roughly Enough Items 15.0.728
			error_notifier: Error Notifier 1.0.9
		rrls: Remove Reloading Screen 4.0.4+mc1.20.5-fabric
		scoreboard-overhaul: Scoreboard Overhaul 1.1.2-mc1.20.5
			scoreboard-overhaul-common: Scoreboard Overhaul 1.1.2-common
		showmapid: ShowMapID 1.0.2+1.20.6
		signcopy: SignCopy 1.1.1
		skinlayers3d: 3d-Skin-Layers 1.6.4
		smoke_signals: Smoke Signals 1.1
		sneakyscreens: Sneaky Screens 1.0.2
		sound_physics_remastered: Sound Physics Remastered 1.20.6-1.3.1
		spark: spark 1.10.65
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
		translucent-glass: Translucent Glass 0.1.3
		universalcraft: UniversalCraft 337
		useful-saved-hotbars: Useful Saved Hotbars 0.1.0+mc1.20.5
		vanillazoom: Vanilla Zoom 2.5
		viafabricplus: ViaFabricPlus 3.2.0
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0
			com_viaversion_viaversion-common: viaversion-common 4.10.0
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			io_netty_netty-codec-http: netty-codec-http 4.1.108
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11
			net_raphimc_viabedrock: ViaBedrock 0.0.6-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22
			net_raphimc_vialoader: ViaLoader 2.2.13
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR3-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			org_yaml_snakeyaml: snakeyaml 2.2
		vigilance: Vigilance 297
		vistas: Vistas 2.6.1
		visuality: Visuality 0.7.4+1.20.5
		vmp: Very Many Players 0.2.0+beta.7.155+1.20.6
		voicechat: Simple Voice Chat 1.20.6-2.5.13
		wi_zoom: WI Zoom 1.5-MC1.20.6
		world_preview: World preview 1.2.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.2+1.20.5-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
		youwereslain: You Were Slain 1.0.0-1.20.x
	Launched Version: 1.20.6
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) HD Graphics 4000 GL version 3.2.0 - Build 10.18.10.4252, Intel
	Window size: 1600x837
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 8/12 chunks
	Resource Packs: vanilla, fabric, alinlib, async-pack-scan, authme, autohud, backburner, bettercommandblockui, betterstats, book_and_quick_save, bundle_scroll, c2me, camoverlay, capes, cardinal-components, cardinal-components-base, cardinal-components-block, cardinal-components-chunk, cardinal-components-entity, cardinal-components-item, cardinal-components-level, cardinal-components-scoreboard, cardinal-components-world, cat_jam, chat_heads, chatshot, cicada, cloth-config, colorfulsubtitles, com_viaversion_viabackwards-common, com_viaversion_viaversion-common, controlify, customclientbrand, customlevelcolour, dynamic_fps, elytratrims (incompatible), entity_texture_features, entityculling, entityseparator, essential (incompatible), essential-container, essential-loader, evilcreativefly, f3teverywhere, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, fan_cake (incompatible), fastquit, fpsreducer, guifollowers (incompatible), immediatelyfast, itemswapper, jade (incompatible), libbamboo, libjf, libjf-config-core-v2, libjf-config-network-v0, libjf-config-ui-tiny, libjf-translate-v1, libjf-web-v1, lighty, listentryhighlightfix, lithium, mambience, map_png, minepedia, modernfix (incompatible), modmenu, morechathistory, moreculling, mr_footprint_particles (incompatible), myresourcepack, net_raphimc_viaaprilfools, net_raphimc_viabedrock, net_raphimc_vialegacy, nodimensionbackground, notebook, oldmclogo, particlerain, peek, pickblockpro, postmortalparticles, pwam, real-arrow-tip, resource_explorer, respackopts, roughlyenoughitems, rrls (incompatible), scoreboard-overhaul, scoreboard-overhaul-common, showmapid, signcopy (incompatible), skinlayers3d, smoke_signals, sound_physics_remastered, spark (incompatible), tcdcommons, translucent-glass, useful-saved-hotbars, vanillazoom (incompatible), viafabricplus, vistas, visuality, vmp, voicechat, wi_zoom, world_preview, yet_another_config_lib_v3 (incompatible), youwereslain, itemswapper:default, itemswapper:experimental_addon, white_icons, file/sus_sand_1.5.zip (incompatible), file/§eExtended_lantern_1.20x.zip (incompatible), file/JadeStardewValleyTheme.zip (incompatible), file/rocketjump.zip (incompatible), file/Alternate Ink.zip (incompatible), file/blackstone-magma.zip (incompatible), file/coal-texture.zip (incompatible), file/da-vinci-gliders.zip (incompatible), file/improved-crafting-table-v1-0.zip, file/§aDrodi's Slimes [Release].zip (incompatible), file/expack-03-caladbolg.zip (incompatible), file/anothercit-v1-0.zip (incompatible), file/RavenPhantoms_v1.0.0.zip (incompatible), backburner:notebook, translucent-glass:translucent-glass, file/pistonmace.zip (incompatible), file/Biomeless Music 1.20.5.zip
	Current Language: en_us
	Locale: en_GB
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz`

### Bug Description

(most) interactions with banners crash the game, i believe it mostly involves breaking the banner, however i got it crashing when hovering over the item

### Steps to Reproduce

Using 1.20.6
use a 1.20.4 server (im using an aternos server)
get any decorated banner and interract with it either by hovering, placing or breaking the block/item

### Expected Behavior

the game suddenly crashes

**Comment by FlorianMichael** [comment]
Hi, thanks for your bug report and sorry for my late response!
I believe this is something we already fixed in dev builds, you should try out this ViaFabricPlus version:
https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/

**Comment by TheUnknownBreeze** [comment]
i've tested it rn, the issue still seems to occur
i used this one [ViaFabricPlus-3.2.1-SNAPSHOT.jar](https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/lastSuccessfulBuild/artifact/build/libs/ViaFabricPlus-3.2.1-SNAPSHOT.jar) in the link you sent me

**Comment by FlorianMichael** [comment]
I'll look into it later, thanks

**Comment by FlorianMichael** [comment]
Issue should be fixed in latest Via* dev builds, until the next ViaFabricPlus release you can:
1. Download ViaVersion jar at https://ci.viaversion.com/job/ViaVersion/
2. Open your .minecraft folder or the folder where your game files are located
3. Open config/viafabricplus/jars and place the downloaded ViaVersion jar in there
4. Restart you game

Thanks for reporting this issue! :)
