### ISSUE TITLE
Network Protocol Error on specific servers

### ISSUE THREAD

**Issue by lrxmri35uord2olu** [ViaVersion/ViaFabricPlus#613]
### General Information

Logs: https://mclo.gs/pzAZX6R
ViaVersion dump: https://dump.viaversion.com/41d8d5bb3a38da508ba3bacdef49608ae8db68cc4a294c023ac11d5d6c1064c7

### Bug Description

Trying to join specific Minecraft servers on 1.21.3 with the ViaFabricPlus version set to 1.21.1 causes you to be disconnected immediately because of a "Network Protocol Error". Reading the logs, I assume this is because of something to do with parsing enchantments that's going wrong.

List of servers affected: (at least the ones that I have tried)
- 2b2t.org
- crystalpvp.cc
- krcrystal.sparked.network
- 6b6t.org
- 8b8t.me

This also happens when trying to join with your client version set to 1.20.6. A workaround for this is setting your viafabric version to 1.20.4 or below, but in very specific cases (such as using a 2b2t proxy) that doesn't work.
I'm unsure if this is strictly a ViaFabricPlus issue and it might be an issue with ViaVersion itself, since joining servers that don't use ViaVersion (such as constantiam.net) with ViaFabricPlus works fine.

### Steps to Reproduce

1. Connecting to one of the servers listed
2. Disconnected by a Network Protocol Error and having errors show up in your log

### Expected Behavior

Connecting to one of the servers listed should not result in an instant disconnect.

**Comment by cursefroge** [comment]
ive only been able to reprod when joining from a unix system running viafabricplus to a server using viaversion or similar. platform-specific library issue?

**Comment by lrxmri35uord2olu** [comment]
> ive only been able to reprod when joining from a unix system running viafabricplus to a server using viaversion or similar. platform-specific library issue?

i'm on macOS so i had a couple of friends that were on windows test this and they still got a network protocol error when trying to join those servers with viafabricplus set to 1.21.1. perhaps something else is different in installations that makes it work for you on windows?

**Comment by cursefroge** [comment]
haven't tested on windows. was just assuming due to the only issues about this being on linux and macos

**Comment by FlorianMichael** [comment]
ViaFabricPlus has no platform specific code and thus all issues will be on all platforms, especially when related to the game's protocol like in this case.

**Comment by FlorianMichael** [comment]
Should work now in dev builds https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/, thank you

**Comment by cursefroge** [comment]
still getting the issue on Hypixel on latest commit, log here: https://mclo.gs/qfp75vJ

**Comment by FlorianMichael** [comment]
@cursefroge Please try again with the newest commit

**Comment by cursefroge** [comment]
works, but seems to crash with Lithium installed: https://0x0.st/Xdo8.txt

**Comment by FlorianMichael** [comment]
That's an unrelated issue, please open a new one then. Although this could be a lithium issue, maybe try without ViaFabricPlus

**Comment by cursefroge** [comment]
made a new bug report. couldn't reproduce without vfp, or on servers that only support 1 version.
