### ISSUE TITLE
1.21.5 Crash on Startup

### ISSUE THREAD

**Issue by Kowaman** [ViaVersion/ViaFabricPlus#771]
### General Information

[crash-2025-05-15_14.29.01-client.txt](https://github.com/user-attachments/files/20232881/crash-2025-05-15_14.29.01-client.txt)

Tested with ViaFabricPlus 4.1.3 and 4.1.4-SNAPSHOT (latest snapshot build)

`fabric-loader-0.16.14-1.21.5`
`fabric-api-0.124.0+1.21.5`

### Bug Description

Crash on startup for 1.21.5. I saw a similar report #770 marked as duplicate (perhaps that was an error as it did not mention the MoreCulling mod that the other reports had), though this is with no other mods installed and testing on the latest snapshot.

### Steps to Reproduce

1. Install fabric
2. Install fabric-api
3. Install ViaFabricPlus
4. Start game

### Expected Behavior

Game launches as expected

**Comment by FlorianMichael** [comment]
Hi. You can download the latest dev build at https://ci.viaversion.com/view/Platforms/job/ViaFabricPlus/ where the issue should be fixed now.

**Comment by Kowaman** [comment]
@FlorianMichael still getting the issue on latest dev build, with latest Fabric-API.

**Comment by Kowaman** [comment]
[crash-2025-06-05_03.28.32-client.txt](https://github.com/user-attachments/files/20605023/crash-2025-06-05_03.28.32-client.txt)

[latest.log](https://github.com/user-attachments/files/20605025/latest.log)

@FlorianMichael
